user-edited: true

stanzas:
  - type: webapp
    exec: ../dist/bin/minibas
    args: []
    hosts:
      - localhost
      - 52.197.94.70
      - minibas.jabara.info
    requires-secure: false
plugins:
  postgres: false
